### ISSUE TITLE
Fix bot breaking on invalid SSL chain

### ISSUE THREAD

**Issue by kokarn** [kokarn/KokBot#26]
```log
{ [Error: unable to verify the first certificate] code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' }
/var/www/ircbot/node_modules/cheerio/lib/parse.js:55
    var oldParent = node.parent || node.root,
                        ^

TypeError: Cannot read property 'parent' of undefined
    at Function.exports.update (/var/www/ircbot/node_modules/cheerio/lib/parse.js:55:25)
    at module.exports (/var/www/ircbot/node_modules/cheerio/lib/parse.js:17:11)
    at Function.exports.load (/var/www/ircbot/node_modules/cheerio/lib/static.js:19:14)
    at UrlcheckerBotPlug.detectEncoding (/var/www/ircbot/plugins/Urlchecker.js:18:25)
    at Request._callback (/var/www/ircbot/plugins/Urlchecker.js:65:29)
    at self.callback (/var/www/ircbot/node_modules/request/request.js:200:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (/var/www/ircbot/node_modules/request/request.js:831:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at TLSSocket.socketErrorListener (_http_client.js:256:9)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at emitErrorNT (net.js:1253:8)
    at nextTickCallbackWith2Args (node.js:442:9)
```

**Comment by kokarn** [comment]
Fixed with https://github.com/kokarn/KokBot/commit/a3ab01e5d13929bc354082058d7fbadfb666cb6d.
